jwt:
  private:
    key: classpath:key
  public:
    key: classpath:key.pub

kafka.server: localhost:29092
kafka.group.id: server.broadcast
kafka.consumer.id: consumerServer
kafka.producer.id: producerServer
